// Code generated by hertz generator.

package user

import (
	"context"
	"github.com/hertz-contrib/sessions"
	"hertz_ucenter/biz/service"
	pkgConsts "hertz_ucenter/pkg/consts"
	"hertz_ucenter/pkg/errno"
	"hertz_ucenter/pkg/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	user "hertz_ucenter/biz/model/hertz/user"
)

// UserRegister .
// @router /v1/user/register [POST]
func UserRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserRegisterRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, user.UserRegisterResponse{
			Code: resp.StatusCode,
			Msg:  resp.StatusMsg,
		})
		return
	}
	userId, err := service.NewUserService(ctx, c).UserRegister(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, user.UserRegisterResponse{
			Code: resp.StatusCode,
			Msg:  resp.StatusMsg,
		})
		return
	}
	c.JSON(consts.StatusOK, user.UserRegisterResponse{
		Code:   errno.SuccessCode,
		Msg:    errno.SuccessMsg,
		UserId: uint64(userId),
	})

}

// UserLogin .
// @router /v1/user/login [POST]
func UserLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserLoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, user.UserLoginResponse{
			Code: resp.StatusCode,
			Msg:  resp.StatusMsg,
		})
		return
	}
	// 判断是否已经登录
	if !utils.IsLogout(ctx, c, req.UserAccount) {
		c.JSON(consts.StatusOK, user.UserLoginResponse{
			Code: errno.UserAlreadyLoginErrCode,
			Msg:  errno.AlreadyLoginMsg,
		})
		return
	}

	loginUser, err := service.NewUserService(ctx, c).UserLogin(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, user.UserLoginResponse{
			Code: resp.StatusCode,
			Msg:  resp.StatusMsg,
		})
		return
	}
	c.JSON(consts.StatusOK, user.UserLoginResponse{
		Code: errno.SuccessCode,
		Msg:  errno.LoginSuccessMsg,
		User: loginUser,
	})
}

// UserLogout .
// @router /v1/user/logout [POST]
func UserLogout(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserLogoutRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, user.UserLoginResponse{
			Code: resp.StatusCode,
			Msg:  resp.StatusMsg,
		})
		return
	}
	if !utils.IsLogout(ctx, c, req.UserAccount) {
		session := sessions.Default(c)
		session.Delete(pkgConsts.UserAccount)
		_ = session.Save()
	}
	c.JSON(consts.StatusOK, user.UserLogoutResponse{
		Code: errno.SuccessCode,
		Msg:  errno.SuccessMsg,
	})
}

// QueryUser .
// @router /v1/user/query [POST]
func QueryUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, user.UserResponse{
			Code: resp.StatusCode,
			Msg:  resp.StatusMsg,
		})
		return
	}

	u, err := service.NewUserService(ctx, c).QueryUserByPage(&req)

	resp := utils.BuildBaseResp(err)
	c.JSON(consts.StatusOK, user.UserResponse{
		Code: resp.StatusCode,
		Msg:  resp.StatusMsg,
		User: u,
	})
}

// UpdateUser .
// @router /v1/user/update/:user_id [POST]
func UpdateUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserUpdateRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UserUpdateResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteUser .
// @router /v1/user/delete/:Id [POST]
func DeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserDeleteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, user.UserDeleteResponse{
			Code: resp.StatusCode,
			Msg:  resp.StatusMsg,
		})
		return
	}
	err = service.NewUserService(ctx, c).DeleteUser(&req)
	if err != nil {
		resp := utils.BuildBaseResp(err)
		c.JSON(consts.StatusOK, user.UserDeleteResponse{
			Code: resp.StatusCode,
			Msg:  resp.StatusMsg,
		})
		return
	}
	c.JSON(consts.StatusOK, user.UserDeleteResponse{
		Code: errno.SuccessCode,
		Msg:  errno.SuccessMsg,
	})
}
